import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Calcular NF-e</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/favicon.png" type="image/png" />
      </Head>

      <h1>Calcular NF-e</h1>
    </>
  )
}
