/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head';
import Link from 'next/link';

import style from '../styles/home.module.scss';

export default function Home() {
  return (
    <>
      <Head>
        <title>Calcular NF-e</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/favicon.png" type="image/png" />
      </Head>

      <div className={style.container}>
        <header>
          <nav>
            <Link href="#">
              <a>Importar XML</a>
            </Link>

            <Link href="/">
              <a>Sobre o projeto</a>
            </Link>

            <Link href="#">
              <a>Ajude o projeto</a>
            </Link>
          </nav>
        </header>

        <main>
          <h1>Calcular custo de produtos na NF-e</h1>

          <p>
            Com tantas dificuldades para empreender no Brasil calcular o custo
            de aquisição de produtos é mais um deles. A Danfe(Documento Auxiliar
            da NF-e) não tem todas as informações necessárias, apenas um resumo,
            e muita das vezes os pequenos empreenderores não tem conhecimento
            para entender e calcular todas as taxas "ocultas".
          </p>

          <p>
            Depois de uma oportunidade de trabalho em uma contabilidade, conheci
            toda essa complexidade do mundo dos impostos. Agora como descobri o
            mundo da programação tive essa ideia, vamos automatizar esse calculo
            e facilitar a vida de quantas pessoas pudermos
          </p>
        </main>

        <footer>
          <p>
            Desenvolvido com 💜 por{' '}
            <a
              href="https://github.com/luiz21goncalves"
              target="_blank"
              rel="noopener noreferrer"
            >
              Luiz Gonçalves
            </a>
          </p>
        </footer>
      </div>
    </>
  );
}
