name: Lint

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: cache node_modules
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

        if: steps.pnpm-cache.outputs.cache-hit != 'true'
      - run: pnpm install --prefer-offline --frozen-lockfile

      - name: run lint
        run: pnpm run lint
